# Site settings
title: Spoke Dynamics
email: team@spokedynamics.com
author: Jordan Russell
description: >- # this means to ignore newlines until "baseurl:"
  Landing page for Spoke Dynamics. Ongoing research and development.
baseurl: "" # the subpath of your site, e.g. /blog
domain: spokedynamics.com
url: https://spokedynamics.com # the base hostname & protocol for your site, e.g. http://example.com

include_nav: false

show_downloads: false

# Build settings
markdown: kramdown

# SASS
sass:
  style: :compressed

# Defaults
defaults:
  - scope:
      path: "*"
    values:
      layout: default


# Exclude
exclude:
  - assets/js/bootstrap.bundle.min.js
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - NOTICE
  - DISCLAIMER